# Generated by Django 5.2.6 on 2025-09-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compartimento', models.IntegerField(choices=[(1, 'Compartimento 1'), (2, 'Compartimento 2'), (3, 'Compartimento 3'), (4, 'Compartimento 4')])),
                ('nombre_pastilla', models.CharField(max_length=100)),
                ('dosis', models.PositiveIntegerField(default=1)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('repeticion', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('CADA_X_HORAS', 'Cada X horas')], max_length=20)),
                ('intervalo_horas', models.PositiveIntegerField(blank=True, null=True)),
                ('hora_toma', models.TimeField(blank=True, null=True)),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
